# Generated by Django 5.1.7 on 2025-04-24 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Felhasznalo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('felhasznalonev', models.CharField(max_length=50, unique=True)),
                ('jelszo', models.CharField(max_length=128)),
                ('utolso_bejelentkezes', models.DateTimeField(blank=True, null=True)),
                ('csatlakozas_ido', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Felhasznalo',
                'verbose_name_plural': 'Felhasznalok',
                'db_table': 'felhasznalok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bejegyzes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feltoltott_kep', models.CharField(blank=True, max_length=128, null=True)),
                ('letrehozasi_ido', models.DateTimeField(blank=True, null=True)),
                ('tartalom', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'bejegyzesek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Csoport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letrehozas_ido', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'csoportok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Komment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feltoltesi_ido', models.DateTimeField(blank=True, null=True)),
                ('tartalom', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'kommentek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzenet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kuldesi_ido', models.DateTimeField(blank=True, null=True)),
                ('tartalom', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'uzenetek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FelhasznaloKapcsolat',
            fields=[
                ('jelolo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('statusz', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'felhasznalo_kapcsolatok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FelhasznaloCsoport',
            fields=[
                ('csoport', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.csoport')),
            ],
            options={
                'db_table': 'felhasznalo_csoportok',
                'managed': False,
            },
        ),
    ]
