-- Felhasználók
CREATE TABLE Felhasznalok (
    id NUMBER(10) PRIMARY KEY,
    felhasznalonev VARCHAR2(50) UNIQUE NOT NULL,
    jelszo VARCHAR2(128) NOT NULL,
    admin NUMBER(1) CHECK (admin IN (0, 1)),
    utolso_bejelentkezes TIMESTAMP,
    csatlakozas_ido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    profil_kep VARCHAR2(128)
);

-- Kapcsolatok
CREATE TABLE Felhasznalo_kapcsolatok (
    jelolo_id NUMBER(10),
    jelolt_id NUMBER(10),
    statusz VARCHAR2(11) CHECK (statusz IN ('pending', 'accepted', 'rejected')),
    PRIMARY KEY (jelolo_id, jelolt_id),
    FOREIGN KEY (jelolo_id) REFERENCES Felhasznalok(id) ON DELETE CASCADE,
    FOREIGN KEY (jelolt_id) REFERENCES Felhasznalok(id) ON DELETE CASCADE
);

-- Csoportok
CREATE TABLE Csoportok (
    id NUMBER(10) PRIMARY KEY,
    felhasznalo_id NUMBER(10),
    letrehozas_ido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (felhasznalo_id) REFERENCES Felhasznalok(id) ON DELETE SET NULL
);

-- Felhasználó Csoportok
CREATE TABLE Felhasznalo_Csoportok (
    csoport_id NUMBER(10),
    felhasznalo_id NUMBER(10),
    PRIMARY KEY (csoport_id, felhasznalo_id),
    FOREIGN KEY (csoport_id) REFERENCES Csoportok(id) ON DELETE CASCADE,
    FOREIGN KEY (felhasznalo_id) REFERENCES Felhasznalok(id) ON DELETE CASCADE
);

-- Üzenetek
CREATE TABLE Uzenetek (
    id NUMBER(10) PRIMARY KEY,
    felhasznalo_id NUMBER(10),
    csoport_id NUMBER(10),
    kuldesi_ido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tartalom VARCHAR2(1000),
    FOREIGN KEY (felhasznalo_id) REFERENCES Felhasznalok(id) ON DELETE SET NULL,
    FOREIGN KEY (csoport_id) REFERENCES Csoportok(id) ON DELETE SET NULL
);

-- Bejegyzések
CREATE TABLE Bejegyzesek (
    id NUMBER(10) PRIMARY KEY,
    felhasznalo_id NUMBER(10),
    feltoltott_kep VARCHAR2(128),
    letrehozasi_ido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tartalom VARCHAR2(1000),
    FOREIGN KEY (felhasznalo_id) REFERENCES Felhasznalok(id) ON DELETE CASCADE
);

-- Kommentek
CREATE TABLE Kommentek (
    id NUMBER(10) PRIMARY KEY,
    felhasznalo_id NUMBER(10),
    bejegyzes_id NUMBER(10),
    feltoltesi_ido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tartalom VARCHAR2(1000),
    FOREIGN KEY (felhasznalo_id) REFERENCES Felhasznalok(id) ON DELETE SET NULL,
    FOREIGN KEY (bejegyzes_id) REFERENCES Bejegyzesek(id) ON DELETE CASCADE
);

-- TABLES FOR DJANGO AUTH. NOT PART OF LINKUP
CREATE TABLE felhasznalok_user_permissions (
    id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    felhasznalo_id NUMBER(11) NOT NULL,
    permission_id NUMBER(11) NOT NULL,
    CONSTRAINT fk_felhasznalok_user FOREIGN KEY (felhasznalo_id) REFERENCES felhasznalok(id),
    CONSTRAINT fk_permission FOREIGN KEY (permission_id) REFERENCES auth_permission(id),
    CONSTRAINT uq_felhasznalok_user_permissions UNIQUE (felhasznalo_id, permission_id)
);


CREATE TABLE FELHASZNALOK_GROUPS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FELHASZNALO_ID NUMBER NOT NULL,
    GROUP_ID NUMBER NOT NULL,
    CONSTRAINT FK_FELHASZNALOK_GROUPS_USER FOREIGN KEY (FELHASZNALO_ID) REFERENCES FELHASZNALOK(ID),
    CONSTRAINT FK_FELHASZNALOK_GROUPS_GROUP FOREIGN KEY (GROUP_ID) REFERENCES AUTH_GROUP(ID),
    CONSTRAINT UQ_FELHASZNALOK_GROUPS UNIQUE (FELHASZNALO_ID, GROUP_ID)
);






